development:
    IMAGO_AWS_ACCESS_KEY_ID: AKIAJGRRSSA7EGQNNL5A
    IMAGO_AWS_SECRET_ACCESS_KEY: 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

  test:
    <<: *development

  production:
    <<: *development