development:
    access_key_id: AKIAJGRRSSA7EGQNNL5A
    secret_access_key: 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

  test:
    access_key_id: AKIAJGRRSSA7EGQNNL5A
    secret_access_key: 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

  production:
    access_key_id: AKIAJGRRSSA7EGQNNL5A
    secret_access_key: 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